[build]
  command = "npm run build"
  functions = "out_functions"
  publish   = ""

[[plugins]]
  package = "@netlify/plugin-next"

[[plugins]]
  package = "@netlify/plugin-emails"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


