[build]
  command = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-next"
[[redirects]]  from = "/*"  to = "/index.html"  status = 200